GSA/smartpay-training

requirements.txt, training/api/api.py, training/api/api_v1/loginless_flow.py, training/config.py, training/data/user_cache.py, training/main.py, training/models/temp_user.py
Sets up the basics for FastApi and some basic settings using Pydantic's BaseSettings
=> Add config for settings and FastAPI

smartpay-training-quiz/src/components/loginless/Loginless.vue, smartpay-training-quiz/src/components/smartpay/Hero.vue
This fixes some minor layout issues to the front end.
=> add responsive column sizes to wrap text appropriately

training/api/api_v1/loginless_flow.py, training/schemas/temp_user.py
Change the jwt in the loginless flow to use data from database and including the user-id.
=> Add user id to loginless flow jwt

training-front-end/src/components/QuizIndex.vue
This includes the user's JWT when making requests to quiz api.
=> add jwt auth header to requests for quiz and quiz sumbission

training-front-end/src/components/TrainingLinks.astro, training-front-end/src/content/training_travel/index.mdx
Addresses #88   
This puts the gray box back on the first page of the training.
=> Callout box

training-front-end/src/components/CertificateTable.vue, training-front-end/src/components/LoginlessFlow.vue, training/tests/factories.py, training/tests/test_quiz_service.py
Addresses remaining issues for #27 
- Includes remaining card icons when showing user certificates
- Changes language around unknown users requesting access to past certificates
=> Design / language tweaks

training-front-end/src/layouts/BaseLayout.astro
Using code from [DAP Guidelines](https://github.com/digital-analytics-program/gov-wide-code/blob/master/documentation/GSA%20DAP%204.1%20-%20Quick%20Guide.pdf)
=> add analytics snippet to base layout

training-front-end/src/content/training_travel_pc/index.mdx, training-front-end/src/content/training_travel_pc/lesson01.mdx, training-front-end/src/content/training_travel_pc/lesson02.mdx, training-front-end/src/content/training_travel_pc/lesson03.mdx, training-front-end/src/content/training_travel_pc/lesson04.mdx, training-front-end/src/content/training_travel_pc/lesson05.mdx, training-front-end/src/content/training_travel_pc/lesson06.mdx, training-front-end/src/content/training_travel_pc/lesson07.mdx, training-front-end/src/content/training_travel_pc/lesson08.mdx, training-front-end/src/pages/training_travel_pc/[...slug].astro, training-front-end/src/pages/training_travel_pc/index.md, training-front-end/src/pages/training_travel_pc/printable.astro
This adds the markdown files for the A/OPC travel training and sets up the astro page with the metadata to link it up the quiz.
=> Program coordinator travel training

manifest-vars.test.yml, manifest.yml
* Create a manifest vars file that can be used to push to the `test` space
* Remove deployer service from the list of services; I don't think it's required here
=> Add cloud.gov test space

training-front-end/astro.config.mjs, training-front-end/package-lock.json, training-front-end/package.json, training-front-end/src/content/training_travel/lesson11.mdx, training-front-end/src/pages/training_travel/printable.astro
Restores the full training printable page.
=> put printable training back

training-front-end/src/components/GSAFooter.astro, training-front-end/src/components/HeroTraining.astro, training-front-end/src/components/MobileNav.astro, training-front-end/src/components/SideNav.astro, training-front-end/src/components/SummaryBox.astro, training-front-end/src/layouts/TrainingLayout.astro, training-front-end/src/pages/training_travel/printable.astro, training-front-end/src/pages/training_travel_pc/printable.astro
- added space between sub header and banner title
- added space for footer
- changed the footer link color 
- Removed the summary box border
- address mobile print issue
- added navigation dropdown list for mobile view and hide side nav for mobile view
=> Fixed issue12

training-front-end/src/components/icons/LogoutIcon.vue
This tweaks the alignment of the exit icon.
=> adjust veritcal alignment on exit icon

training-front-end/src/components/GSAFooter.astro, training-front-end/src/layouts/TrainingLayout.astro
- Added more spacing for mobile navigation
- Adjust spacing for footer, make it 1em for mobile view and 2em for desktop view.
=> adjust spacing per QA comments

training-front-end/src/content/training_purchase/index.mdx, training-front-end/src/content/training_purchase/lesson01.mdx, training-front-end/src/content/training_purchase/lesson02.mdx, training-front-end/src/content/training_purchase/lesson03.mdx, training-front-end/src/content/training_purchase/lesson04.mdx, training-front-end/src/content/training_purchase/lesson05.mdx, training-front-end/src/content/training_purchase/lesson06.mdx, training-front-end/src/content/training_purchase/lesson07.mdx, training-front-end/src/content/training_purchase/lesson08.mdx, training-front-end/src/content/training_purchase/lesson09.mdx, training-front-end/src/content/training_purchase/lesson10.mdx, training-front-end/src/content/training_purchase/lesson11.mdx, training-front-end/src/content/training_purchase/lesson12.mdx, training-front-end/src/pages/training_purchase/printable.astro
- Adds the training documents as .mdx files
- Sets up astro page to use content.
=> Purchase Training

README.md, bin/cg-bootstrap-app.sh, bin/cg-bootstrap-space.sh, bin/cg-service-account-create.sh, bin/cg-service-account-delete.sh, bin/cg-service-account-rotate.sh, bin/cg-set-env.sh, bin/cg-set-secret.sh
- Add some info about the `test` space to the readme
- Add a note about needing the `SpaceDeveloper` role to the readme
- Add a script to help with creating secrets
- Update the scripts to quit immediately if they encounter an error
=> Various improvements related to deployment

training-front-end/src/components/LoginlessFlow.vue, training-front-end/src/components/SpinnerGraphic.vue
added mobile view design per Mel's design suggestion
=> update the mobile view design

training-front-end/src/content/training_purchase_pc/index.mdx, training-front-end/src/content/training_purchase_pc/lesson01.mdx, training-front-end/src/content/training_purchase_pc/lesson02.mdx, training-front-end/src/content/training_purchase_pc/lesson03.mdx, training-front-end/src/content/training_purchase_pc/lesson04.mdx, training-front-end/src/content/training_purchase_pc/lesson05.mdx, training-front-end/src/content/training_purchase_pc/lesson06.mdx, training-front-end/src/content/training_purchase_pc/lesson07.mdx, training-front-end/src/content/training_purchase_pc/lesson08.mdx, training-front-end/src/content/training_purchase_pc/lesson09.mdx, training-front-end/src/pages/training_purchase_pc/[...slug].astro, training-front-end/src/pages/training_purchase_pc/printable.astro
Added training material for purchase training AOPC
=> Resolve issue 59- training material AOPC

training/repositories/agency.py
Add Collate in order by, and resolve default order by name asc doesn't take special character into consideration issue
=> adding collation to it for sort

Dockerfile.uaadev, docker-compose.yaml, uaadev.yml
Add a local UAA server for development ahead of adding admin login functionality.
=> Add local UAA server

training/api/api_v1/auth.py, training/api/api_v1/loginless_flow.py, training/api/api_v1/users.py, training/config.py, training/main.py, training/tests/test_api_users.py
Adds audit logging per:
* https://github.com/GSA/smartpay-training/issues/210
* https://github.com/GSA/smartpay-training/issues/211
=> Add some audit logging

.github/workflows/backend-tests.yaml, training/database/database.py
This updates the connection string to force ssl connections with the database.
=> change db connection string to use ssl

training-front-end/package-lock.json
Fixes a couple moderate security issues from Dependabot.
=> update semver to non-vulnerable version

.github/workflows/deploy-staging.yaml, training-front-end/.env.production, training/api/api_v1/quizzes.py, training/repositories/user.py
- when creating new user,  save email address is lower case to DB
- when searching if user exists in DB, use lower case email input to search
- On hold: clean up DB and make sure email address are saved in lower case only
=> address email case sensitive issue

training-front-end/src/components/SessionManager.vue, training-front-end/src/stores/session_manager.js
- Adds the word `to` to the alert given to users when exiting.
=> Small edit to exit alert message requested by program

manifest-vars.dev.yml, manifest-vars.staging.yml, training-front-end/src/services/auth.ts
This changes oauth urls to point to staging front-end.
=> fix oauth redirect urls for admin login

training-front-end/src/components/SessionManager.vue, training-front-end/src/stores/session_manager.js
Simplify exit message based on content conversation with program and Ryan.
=> simplify langauage of exit notification

training-front-end/src/components/AdminIndex.vue, training-front-end/src/components/AdminSearchUser.vue, training/api/api_v1/users.py, training/repositories/user.py, training/tests/test_api_users.py, training/tests/test_user_repository.py
UI needs updates as well, revert previous changes on dev
=> Revert "refactoring users, and remove unused page/fuctions"

data/seedsdata.yaml, training-front-end/src/components/LoginlessFlow.vue, training/database/seed.py, training/repositories/agency.py
- update the final agency list
- added new bureaus
- put 'Other' agency /bureau at the end of list 
code is deployed to dev, db data also cleaned up on dev environment.
=> update the final agency list

training/tests/test_agency_repository.py, training/tests/testdata.yaml
Adds unit tests for agency repo to test sorting code.
=> Add tests for sort order in agency repo

training/tests/test_api_loginless_flow.py
Adds a few more tests mostly to cover failure paths in loginless API.
=> bring loginless api test coverage to 100%

training/main.py
Update CORS settings to remove wildcard origin.
=> remove the wildcard CORS origin and add origins to help with local dev

training-front-end/src/components/QuizQuestion.vue, training-front-end/src/components/TrainingAccounts.astro, training-front-end/src/components/TrainingCard.astro, training-front-end/src/components/ValidatedInput.vue, training-front-end/src/pages/index.astro
- update training card structure to support aria-label for both training and quiz
- added comments
- correct typo
=> address additional accessibility audit findings 

training-front-end/src/components/LoginlessFlow.vue, training-front-end/src/components/TrainingReportIndex.vue, training-front-end/src/content/training_travel_pc/lesson03.mdx, training-front-end/src/pages/index.astro
- added missing ® to GSA SmartPay
=> added the missing Rs

training-front-end/src/components/AuthRedirect.vue
merge into dev to test back end code change
=> address home page URl issue

training-front-end/src/content/training_fleet_pc/lesson01.mdx, training-front-end/src/content/training_fleet_pc/lesson03.mdx, training-front-end/src/content/training_purchase/lesson04.mdx, training-front-end/src/content/training_purchase/lesson06.mdx, training-front-end/src/content/training_travel/lesson05.mdx
Some final changes to training content after UAT.
=> Jessica marine1 patch 1

training-front-end/src/content/training_purchase/lesson03.mdx
- One more path update to new website
=> One more link update 🤞

training-front-end/.env.dev, training-front-end/.env.development, training-front-end/.env.staging
Sets environment for timeouts to 30 minutes.
=> Change timeouts on user sessions from 60 minutes to 30 minutes

requirements.txt
=> add gunicorn to requirements

data/seedsdata.yaml, training/database/seed.py, training/models/user.py
- added AOPCs preloading data
- added data handling for aopc preloading data
- added new bureaus to support aopc data loading
- corrected SP team member Sarah's email address
=> preloading AOPCs data

training-front-end/src/components/QuizMain.vue, training-front-end/src/components/__tests__/QuizMain.spec.js
merge into dev for backend change testing
=> per issue 364, remove lower case of topic

training/api/api_v1/agencies.py, training/api/api_v1/quizzes.py, training/tests/test_api_agencies.py
- Remove agency creation end point as it is not used from UI
- disable the quiz creation
=> disable quiz creation, remove unused agency creation

data/seedsdata.yaml
- added new agency: Other Agencies/Organizations
- update existing agency for Native American Tribal Governmentsand Other Boards and Commissions
- updated aopc list accordingly
=> update aopc list

data/seedsdata.yaml
removed extra bureau for DOD users
=> updated the AOPC list

training-front-end/src/components/AdminEditReporting.vue, training-front-end/src/pages/training_fleet_pc/printable.astro, training-front-end/src/pages/training_purchase/printable.astro, training-front-end/src/pages/training_purchase_pc/printable.astro, training-front-end/src/pages/training_travel/printable.astro, training-front-end/src/pages/training_travel_pc/printable.astro
- Fixed email label on admin pannel
- Fixed the printable page banner color
=> address the bugs

data/seedsdata.yaml, training/database/seed.py
- update the final agency update per PO's request
- added AOPC skip condition to avoid data conflicts and added comment.
=> update the agency per PO new update. Add comments

README.md
This PR updates the README file for clarity about setting up for development and testing. Specifically:
* Update instructions for .env file to include information about setting up development email (via ethereal)
* Update .env instructions to specify locally hosted BASE_URL
* Update database setup, migration, and training quiz import instructions
* Update node enviroment setup instructions
* Update testing instructions
=> Updating README with dev and test setup details

training/main.py
Fix and error in the CORS origin domain 😬 .
=> fix typo in cors domain

training-front-end/src/content/training_fleet_pc/lesson08.mdx, training-front-end/src/content/training_travel_pc/lesson06.mdx
Updated two outdated links on the newly launched training site.
=> Rebekah100723

training-front-end/src/components/QuizMain.vue, training/api/api_v1/users.py
- added spinner for quiz submit to give user visual cue it is in progress for slow connection
- changed the "Quiz Completion Date to "Quiz Completion Date and Time" for UI display to distinguish records.
=> address quiz completion report bug

training-front-end/src/components/Hero.astro, training-front-end/src/pages/index.astro
Header update. Shorten the header text and added additional padding to header section.
Ticket: https://github.com/GSA/smartpay-training/issues/431
Preview Branch: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/feature/issue-431/update_training_site_header/
=> Updated Website header.

training-front-end/src/components/AdminSearchUser.vue, training-front-end/src/components/__tests__/AdminSearchUser.spec.js, training/api/api_v1/users.py, training/repositories/user.py, training/tests/test_api_users.py, training/tests/test_user_repository.py
Issue: https://github.com/GSA/smartpay-training/issues/203
Preview branch: https://federalist-2e11f2c8-970f-44f5-acc8-b47ef6c741ad.sites.pages.cloud.gov/preview/gsa/smartpay-training/feature/issue-203/search_user_by_email/
=> Allow admin to search users by name or email

training/services/__init__.py, training/services/quiz.py, training/tests/conftest.py, training/tests/test_quiz_service.py
Updated grade quiz service method to send email with certificate attached when user has successfully passed their quiz.
Updated existing unit test to reflect service method changes.
=> Feature/issue 232/email certificate

training-front-end/src/components/QuizResults.vue, training-front-end/src/components/__tests__/QuizResults.spec.js
Updated language that displays when user passes a quiz to indicate certificate will be emailed to the user.
=> Update passing quiz completion language

training-front-end/src/content/training_fleet_pc/lesson01.mdx, training-front-end/src/content/training_purchase/lesson01.mdx, training-front-end/src/content/training_purchase_pc/lesson01.mdx, training-front-end/src/content/training_travel/lesson01.mdx, training-front-end/src/content/training_travel_pc/lesson01.mdx
This PR updates content about recognizing cards/accounts to match with the program website.
=> Rebekah112423

training-front-end/package-lock.json, training-front-end/package.json
Updated oidc-client-ts library version to address vulnerability in transitive dependency (crypto-js)
=> Library Update Due to Known Vulernability

requirements.txt
Updated fast api library from 0.101.0 to 0.109.1
Updated python multipart library from 0.0.6 to 0.0.7
=> Dependabot Vulnerability Update

training-front-end/src/components/USAIdentifier.astro
https://github.com/GSA/smartpay-training/issues/508
=> update footer link text.

training-front-end/package-lock.json
Refreshed the package-lock to update dependent packages. Smoked tested, ran through, and took a quiz. 
https://github.com/GSA/smartpay-training/issues/498
=> Update npm packages.

training-front-end/package-lock.json, training-front-end/src/components/AdminEditReporting.vue, training-front-end/src/components/AdminEditUserDetails.vue, training-front-end/src/components/AdminSearchUser.vue, training-front-end/src/components/USAIdentifier.astro, training-front-end/src/components/ValidatedInput.vue, training-front-end/src/components/ValidatedSelect.vue, training-front-end/src/components/__tests__/AdminEditReporting.spec.js, training-front-end/src/content/training_purchase/lesson05.mdx, training-front-end/src/content/training_purchase_pc/lesson03.mdx, training-front-end/src/pages/admin/index.astro, training/api/api_v1/users.py, training/repositories/user.py, training/schemas/__init__.py, training/schemas/user.py, training/tests/test_api_users.py, training/tests/test_user_repository.py
Includes:
Issue #498 Dependabot Alert: NPM IP package vulnerable to Server-Side Request Forgery (SSRF) attacks
Issue #181 Administrator | Edit User
Issue #508 Footer Changes for SmartPay Training Site 
Issue #504 Update A/OPC Training Content Lesson 3
=> Production Release

training/api/email.py
https://github.com/GSA/smartpay-training/issues/510
=> Update GSPC email.py

training-front-end/src/content/training_fleet_pc/lesson01.mdx, training-front-end/src/content/training_purchase/lesson01.mdx, training-front-end/src/content/training_purchase_pc/lesson01.mdx, training-front-end/src/content/training_travel/lesson01.mdx, training-front-end/src/content/training_travel_pc/lesson01.mdx
Issue #544 remove the cost benefit savings information
=> Remove benefit content

training-front-end/src/content/training_fleet_pc/lesson01.mdx, training-front-end/src/content/training_purchase/lesson01.mdx, training-front-end/src/content/training_purchase_pc/lesson01.mdx, training-front-end/src/content/training_travel/lesson01.mdx, training-front-end/src/content/training_travel/lesson05.mdx, training-front-end/src/content/training_travel_pc/lesson01.mdx
https://github.com/GSA/smartpay-training/issues/539
=> Update CCP links.

training-front-end/src/content/training_fleet_pc/lesson01.mdx, training-front-end/src/content/training_purchase/lesson01.mdx, training-front-end/src/content/training_purchase_pc/lesson01.mdx, training-front-end/src/content/training_travel/lesson01.mdx, training-front-end/src/content/training_travel_pc/lesson01.mdx
Content updates for text corrections, typos, and style updates for May 2024.
=> 552 Training Website Content Changes - May

training-front-end/src/components/GspcQuestions.vue, training-front-end/src/components/GspcRegistration.vue, training/services/gspc.py, training/tests/conftest.py, training/tests/factories.py, training/tests/test_gspc_service.py, training/tests/testdata.yaml
Fixed home links and added more tests.
=> Fixed home links and added more tests.

training-front-end/src/pages/admin/index.astro
**BUG: Update the GSPC URL:**
https://github.com/GSA/smartpay-training/issues/562
=> Refix admin gspc link.

training-front-end/package-lock.json, training-front-end/src/components/CertificateTable.vue, training-front-end/src/components/GspcRegistration.vue, training-front-end/src/components/QuizResults.vue, training-front-end/src/components/__tests__/CertificateTable.spec.js, training-front-end/src/pages/admin/index.astro, training/api/api_v1/certificates.py, training/api/auth.py, training/repositories/certificate.py, training/schemas/__init__.py, training/schemas/user_certificate.py, training/tests/test_api_certificates.py, training/tests/test_certificate_repository.py
BUG: Update the GSPC URL #562
User can view GSPC Certificates on Access Past Certificates #556 
Question 14: Purchase A/OPC Training: Deactivation and reactivation #563 
Question 3. Purchase Card/Account Holder Training Quiz #551 
Question 23: Card/Account Holders and Approving Officials Purchase Training Quiz #462
=> Merging Sprint 31 stories

training-front-end/src/pages/training_fleet_pc/printable.astro, training-front-end/src/pages/training_purchase/printable.astro, training-front-end/src/pages/training_purchase_pc/printable.astro, training-front-end/src/pages/training_travel/printable.astro, training-front-end/src/pages/training_travel_pc/printable.astro
Download Name for Tab and PDF Saving Needs Corrected
[#460](https://github.com/GSA/smartpay-training/issues/460)
=> Update corse printable pages titles.

training-front-end/src/components/GspcQuestions.vue, training-front-end/src/components/__tests__/GspcQuestions.spec.js
User Research Feedback - UI Changes to GSPC
[#604](https://github.com/GSA/smartpay-training/issues/604)
=> gspc-modifications.

training-front-end/src/components/AdminEditReporting.vue
Admin: Deleting Reporting Access in the UI is not deleting the record in the Database
[#605](https://github.com/GSA/smartpay-training/issues/605)
=> Save on report access removal.

training-front-end/src/components/AdminEditReporting.vue, training-front-end/src/components/AdminEditUserDetails.vue, training-front-end/src/components/AdminRepository.vue, training-front-end/src/components/AdminSearchUser.vue, training-front-end/src/components/RepositoryFactory.vue, training-front-end/src/components/__tests__/AdminEditReporting.spec.js, training-front-end/src/components/__tests__/AdminSearchUser.spec.js, training/api/api_v1/users.py, training/tests/test_api_users.py
User Profile > Save Changes Without Returning the User to the Search Results Screen
[#621](https://github.com/GSA/smartpay-training/issues/621)
=> Feature/621 User Profile

.gitignore, training-front-end/src/components/AdminEditReporting.vue, training-front-end/src/components/AdminEditUserDetails.vue, training-front-end/src/components/AdminRepository.vue, training-front-end/src/components/AdminSearchUser.vue, training-front-end/src/components/RepositoryFactory.vue, training-front-end/src/components/__tests__/AdminEditReporting.spec.js, training-front-end/src/components/__tests__/AdminSearchUser.spec.js, training-front-end/src/content/training_fleet_pc/lesson03.mdx, training-front-end/src/content/training_purchase/lesson05.mdx, training-front-end/src/content/training_purchase_pc/lesson03.mdx, training-front-end/src/content/training_travel/lesson03.mdx, training-front-end/src/content/training_travel_pc/lesson03.mdx, training/api/api_v1/certificates.py, training/api/api_v1/users.py, training/tests/test_api_certificates.py, training/tests/test_api_users.py
- Titles of FASCA and Drone in all Trainings #616
- User Profile > Save Changes Without Returning the User to the Search Results Screen #621
- Bug: Admin User unable to download another user's certificate #623
- Dependabot Alert: Server-Side Request Forgery in axios #620
=> GSA Production Release

training-front-end/src/content/training_fleet_pc/lesson03.mdx, training-front-end/src/content/training_purchase/lesson05.mdx, training-front-end/src/content/training_purchase_pc/lesson03.mdx, training-front-end/src/content/training_travel/lesson03.mdx, training-front-end/src/content/training_travel_pc/lesson03.mdx
BUG: Update Titles on FASCSA and Drone
[#631](https://github.com/GSA/smartpay-training/issues/631)
=> Update header level for training.

training-front-end/src/content/training_fleet_pc/lesson01.mdx, training-front-end/src/content/training_purchase/lesson01.mdx, training-front-end/src/content/training_purchase_pc/lesson01.mdx, training-front-end/src/content/training_travel/lesson01.mdx, training-front-end/src/content/training_travel_pc/lesson01.mdx
Sprint 40 Content changes
[#656](https://github.com/GSA/smartpay-training/issues/656)
=> Lesson 01 content changes.

training-front-end/public/robots.txt, training-front-end/src/components/GSAHeader.astro
Add search.gov search to training site.
=> Gsa/issue 635/add search

training-front-end/src/content/training_purchase/lesson04.mdx, training-front-end/src/content/training_purchase_pc/lesson03.mdx
New biobased content added to both purchase training
=> New content/663 biobased in training

training-front-end/src/components/CertificateIndex.vue, training-front-end/src/components/GspcRegistration.vue, training-front-end/src/components/QuizIndex.vue, training-front-end/src/stores/__tests__/user.spec.js, training-front-end/src/stores/user.js
Consistent Message Displayed on Expired/Invalid Links
[#630](https://github.com/GSA/smartpay-training/issues/630)
=> Update the loggin error alerts to be consistant accross the sight.

training-front-end/src/components/AdminEditReporting.vue, training-front-end/src/components/AdminEditUserDetails.vue, training-front-end/src/components/AdminTrainingReport.vue, training-front-end/src/components/LoginlessFlow.vue, training-front-end/src/components/USWDSComboBox.vue, training-front-end/src/components/__tests__/Loginless.spec.js, training-front-end/src/components/__tests__/USWDSComboBox.spec.js, training-front-end/src/components/form-components/USWDSComboBox.vue
Replaced USWDS select component with USWDS component for agency and bureau fields. Changes were made on loginless flow page, admin user edit, and generate training report.
=> Gsa/issue 54/update dropdown

training/config.py
Update SMTP email Header from field from smartpay-noreply@gsa.gov to smartpay_do_not_reply@gsa.gov
=> Update SMTP config settings

training/repositories/user.py
Update report download logic to include all quiz completions for the user bureaus when user selects agency only
=> Report download bug

training/repositories/user.py
Updated admin report download logic to include all quiz completions for the user bureaus when admin selects agency only
=> Admin Training Report download updates
