GSA/smartpay-training

- training/database/database.py
Now that we're using Alembic for migrations, this bit of code telling SQLAlchemy to automatically create tables should actually be removed.
> Fix database migration

- training-front-end/src/components/Quiz.vue
- training-front-end/src/components/QuizIndex.vue
- training-front-end/src/components/QuizResults.vue
- Removes the `beforeunload` handler when the quiz unmounts so navigating away from quiz results does not ask 'are you sure'.
- Removes the unneeded `beforeunload` on quiz results
> remove the beforeunload handler after the quiz is submitted

- training-front-end/src/components/Quiz.vue
- training-front-end/src/components/TrainingLinks.astro
- Replaces #107 (that branch included changes no longer relevant, such as including additional ® instance)
- Recases two instances of title case in buttons
> Recase buttons to sentence case

- training/schemas/__init__.py
- training/schemas/quiz.py
- training/schemas/quiz_question.py
- training/tests/conftest.py
- training/tests/test_quiz_repository.py
- training/tests/test_quiz_schemas.py
- training/tests/testdata.yaml
We're using string constants for some non-normalized database columns, namely quiz topic, quiz audience, and question type. This adds validation enforcement on those fields to ensure they only accept correct values.
> Enforce validation on quiz topic/audience and question type fields

- training-front-end/package-lock.json
- training-front-end/package.json
- training-front-end/src/components/LoginlessFlow.vue
This replaces the fork of Vuelidate (the library we use for form validation) with the original. We originally used a fork because of a small problem with how it was packaged that prevented it from building with Astro. Vuelidate fixed this in the most recent version so we no longer need to custom fork.
Also updates front-end libraries to the latest versions.
> Update front-end dependencies

- .github/workflows/backend-tests.yaml
- .github/workflows/deploy.yaml
- .github/workflows/frontend-tests.yaml
In this change:
* Changes within the `training-front-end` directory trigger front end tests, but not backend tests or cloud.gov deployment
* Changes outside of the `training-front-end` directory trigger backend tests and cloud.gov deployment, but not front end tests
> Run GitHub Actions only when appropriate

- .env_example
- training/api/api_v1/loginless_flow.py
- training/api/email.py
- training/config.py
`fastapi_mail` seems to always require a username/password even when one does not exist for the SMTP server. This switches over to `smtplib` and makes the SMTP user/pass optional.
> Refactor to work with SMTP servers without auth

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-staging.yaml
- .github/workflows/deploy.yaml
- bin/cg-bootstrap-space.sh
- manifest-vars.prod.yml
- manifest-vars.staging.yml
This rounds out the implementation of a full set of deployment workflows for `dev`, `staging`, and `prod` spaces on cloud.gov. It is modeled after the [FAC deployment process](https://github.com/GSA-TTS/FAC/blob/main/docs/deploying.md#standard-deployment-process).
tl;dr:
* Push to `main` = deployment to `dev` space
* Push to `prod` = deployment to `staging` space
* Create a tag in the format `release-*` = deployment to `prod` space
BTW, for the record, we also have a `test` space, but for that space we're just doing manual deployment so that we can hand pick items for testers to test.
> Add staging and production deployment workflows

- .github/workflows/deploy-dev.yaml
- .github/workflows/deploy-prod.yaml
- .github/workflows/deploy-staging.yaml
- .github/workflows/deploy.yaml
Secrets aren't automatically accessible to the child deploy workflows, so deployment fails. This update specifies that secrets should be inherited from the parent workflow.
> Fix the new deploy actions

- training-front-end/src/components/GSAFooter.astro
- Changes program website link text to conform to style guide
- Adds `GSA` to `SmartPay`
-  Changes `site` to `website`
> Style guide change to footer smartpay reference

- training-front-end/src/components/LoginlessFlow.vue
- training/api/api_v1/loginless_flow.py
- training/api/email.py
- training/errors.py
This change corrects the link for the "Not the right email? Send another email" link (issue #201).
Also, it removes the dev link from the confirmation email flow, since emails should be working properly now.
> Correct email retry link

- training-front-end/src/components/AdminAgencySelect.vue
- training-front-end/src/components/TrainingReportDownload.vue
- training-front-end/src/components/TrainingReportIndex.vue
- Corrects the `select all` link changing it to `Select all` 
- Fixes a couple warning coming from the linter.
> use upper case for 'Select all'; fix a couple linting warnings

- manifest.yml
- training/api/api_v1/auth.py
- training/schemas/user.py
- training/tests/factories.py
- training/tests/test_auth_login.py
- training/tests/test_user_schema.py
This updates `/auth/exchange` to issue a JWT only if the user has the `Admin` role. At this point, we do not expect that anyone other than admins will use SecureAuth to login. Having a single authorization failure point will make it more straightforward to display an unauthorized error message on the front end.
> Adjust flow to deny token exchange for non-admins

- training-front-end/src/components/TrainingReportDownload.vue
- training-front-end/src/components/__tests__/TrainingReportIndex.spec.js
Changes training report component to expect a list of role names in user rather than list of objects when determining is someone has a "Report" role. Closes #250
> Accommodate change in user.roles 

- training-front-end/package-lock.json
- training-front-end/package.json
To fix dependency vulnerabilities, this bumps versions of 
- Astro (and mdx, vue, and sitemap plugins) to latest versions
- USWDS to 3.5.0
> upgrade Astro versions to remove Vite severe vulnerability

- training-front-end/src/services/auth.ts
The auth metadata stored in localStorage is specific to each environment. When we started using multiple environments, this presented a problem where the user would not be able to log in unless they manually went in to clear their localStorage data. This change switches from using localStorage to sessionStorage. That way, the user just has to end their session in order to be able to sign in to a different environment.
> Save auth metadata in session storage

- training/main.py
This removes the wildcard CORS setting to address the low security finding around cross-origin requests. It also adds localhost domains to avoid errors when running locally.
> remove the wildcard CORS origin and add origins to help with local dev

- training/repositories/certificate.py
This fixes #315 — when we changed the schema of the certificates to include the agency, we overlooked that the certificate listing also returns a list of these objects. The validation was failing since these did not have the agency.
> get agency when getting certificates to schema validates correctly

- training-front-end/src/pages/quiz/[training_id].astro
Changes the title for travel training for program coordinators to be consistent with other a/opc training. The email will now read:
> Click the link below to access your GSA SmartPayⓇ Travel Training for Program Coordinators quiz.
> Make A/OPC travel training title consistent.

- training/api/auth.py
- training/tests/test_auth.py
- training/tests/test_auth_login.py
- Removes redundant logic from HTTPAuth subclass. FastApi's [HTTPBearer class](https://github.com/tiangolo/fastapi/blob/bfde8f3ef20dc338bbce8a0ff0f4b441c54d5b64/fastapi/security/http.py#L100C7-L100C17) already tests for the inclusion of the `bearer` scheme and `credentials` and will raise a 403 exception if these are not present. The code removed was not reachable. 
- Adds a few more tests for the edge cases, and to improve coverage.
> Improve test coverage

- training-front-end/src/components/TrainingReportDownload.vue
- training-front-end/src/components/TrainingReportIndex.vue
- training-front-end/src/content/training_purchase/lesson03.mdx
- training/api/email.py
- training/tests/test_email.py
-  Search for Smartpay to ensure P is capitalized everywhere
-  Make sure "GSA" precedes every reference to SmartPay
-  Ensure that the (R) mark is only used on the first reference on each page / document
> address content issue

- training-front-end/src/components/AuthRedirect.vue
for user that are not admin user, if they try to use admin portal, it will have error message and Go back to Home link, previously the Go back to home link render 404 error, code fix is merged and deployed in dev branch for back end testing
> address home page URl 404 issue

- manifest-vars.prod.yml
- training-front-end/.env.production
Bring memory in line with current deployed use. Connect prod front-end to prod backend
This also changes the memory use. 4GB was crashing with memory errors. We can try to push this up after we confirm things are working.
> Change Prod Env

- training-front-end/src/pages/training_fleet_pc/printable.astro
- training-front-end/src/pages/training_purchase/printable.astro
- training-front-end/src/pages/training_purchase_pc/printable.astro
- training-front-end/src/pages/training_travel/printable.astro
- training-front-end/src/pages/training_travel_pc/printable.astro
This fixes and issue that prevented tables from rendering correctly in the "printable" view of the trainings. It also make headings and line lengths more closely match the rendering on the site.
> wrap content in usa-prose to make tables work on printable pdf

- training/main.py
We learned during the migration of the 889 to cloud.gov that the pattern of having both an origin list and a regex did not work and caused CORS errors. This explicitly sets origins and removes the regex.
> make CORS origins explicit — using both origin list and regex is not working

- training-front-end/src/components/QuizMain.vue
The adds a flag to indicate if the user has submitted a quiz and disables the submit button when they have. This is to prevent double clicks from creating multiple records in the database. [Note: this is quick fix, it may be better to show a spinner to indicate things are working for users on slow connections]
> prevent multiple clicks of submit button

- training-front-end/src/components/TrainingCard.astro
As described in #441 this is a nuanced accessibility flag, which requires a matching string for accessible labels and visual text.
This fix isn't ideal, since it coerces the accessible name into a matching string. But there's a unique accessible case for doing so, described in [this article](https://dequeuniversity.com/rules/axe/4.8/label-content-name-mismatch) and the [WCAG guidance](https://www.w3.org/WAI/WCAG22/Understanding/label-in-name.html):
> Speech input users can interact with a webpage by speaking the visible text labels of menus, links, and buttons that appear on the screen. It is confusing to speech input users when they say a visible text label they see, but the speech command does not work because the component's accessible (programmatic) name does not match the visible …
> Resolves accessibility flag for WCAG 2.1 compliance

- training/services/quiz.py
- training/tests/conftest.py
- training/tests/test_quiz_service.py
Updated quiz service grade and email certificate unit test. Increased quiz service unit test coverage.
> Updated Unit Test Coverage

- training-front-end/src/components/GspcQuestions.vue
- training-front-end/src/components/QuizMain.vue
Position of the Back Button on Mobile
[#398](https://github.com/GSA/smartpay-training/issues/398)
> Update back button styling.

- training-front-end/src/pages/training_fleet_pc/printable.astro
- training-front-end/src/pages/training_purchase/printable.astro
- training-front-end/src/pages/training_purchase_pc/printable.astro
- training-front-end/src/pages/training_travel/printable.astro
- training-front-end/src/pages/training_travel_pc/printable.astro
Accessibility Bug: Buttons without Accessible Names on all Trainings Print Training Functionality
[#591](https://github.com/GSA/smartpay-training/issues/591)
> Add aria labels to print buttons.

- training-front-end/src/components/AdminEditUserDetails.vue
When editing your user profile, a system error is displayed. However, the spinner persists on the page and the buttons are disabled. A user has to refresh the page for the button to be enabled.
> Update spinner to stop when error is retuned.

- training-front-end/src/components/form-components/ValidatedSelect.vue
BUG: The Agency/Bureau drop-down doesn't not allow a user to deselect a value
[#686](https://github.com/GSA/smartpay-training/issues/686)
> Allow user to clear optional select boxes.

- training-front-end/src/components/AdminSearchUser.vue
Refreshed admin search result on cancel from the edit reporting page as you can also update user details on the page without updating the reporting access. Refresh page to display updated details.
> Refresh admin search results when canceling edit from report editing page

- .github/workflows/fod-scan.yaml
- training-front-end/package-lock.json
- training-front-end/package.json
Sprint 54 issues include:
Integration to Application Security as a Service (AppSECaaS) #654
Dependabot Alert: Vite has an server.fs.deny bypass with an invalid request-target #808 
Dependabot Alert: Vite has a server.fs.deny bypassed for inline and raw with ?import query #800 
Dependabot Alert: Vite allows server.fs.deny to be bypassed with .svg or relative paths 83 #799 
Dependabot Alert: Vite bypasses server.fs.deny when using ?raw?? #801 Dependabot Alert: Babel has inefficient RexExp complexity in generated code with .replace when transpiling named capturing groups #789 
Dependabot Alert: PrismJS DOM Clobbering vulnerability #783 
Upgrade to Astro 5.0 #795
Dependabot Alert: esbuild enables any website to send any requests to the development server and read the response #762
> Production Release

- training-front-end/src/components/__tests__/ValidatedCheckboxGroup.spec.js
- training-front-end/src/components/form-components/ValidatedCheckboxGroup.vue
Add select all feature to checkbox group component
> Gsa/issue 827/select all quiz types
